import React from 'react';
import rawCatalog from './catalog.json';
import {Bonus,Catalog,Effect,Job,Mode,Result,Side,Weapon} from './types';
import {effectFields,effectLabel,makeModels,pack,sourceBonus,uid} from './model';
import './simulation.css';
import IncDecSelect from 'src/components/IncDecSelect';
import {createSimulationWorker} from 'src/lab/createWorkers';
import useCalculationWorker from 'src/lab/useCalculationWorker';
import {EmptyResult,ModeSwitch,PageHeading,ResultNotice,ResultsHeader,RunPanel,ScenarioActions} from 'src/lab/LabUi';
const catalog=rawCatalog as Catalog;
const usableTeams=catalog.teams.filter(t=>t.operatives.length>0);
const pct=(v:number)=>(v*100).toFixed(1)+'%';
const interval=(p:number,n:number)=>{const z=1.96,d=1+z*z/n,c=(p+z*z/(2*n))/d,r=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return `${(Math.max(0,c-r)*100).toFixed(2)}–${(Math.min(1,c+r)*100).toFixed(2)}%`;};
const byTeam=(id:string)=>usableTeams.find(t=>t.id===id)||usableTeams[0];
function createSide(teamId:string,opHint=''):Side{const t=byTeam(teamId);const o=(opHint?(t.operatives.find(o=>o.id===opHint)||t.operatives.find(o=>o.id.includes(opHint))):t.operatives.find(o=>/warrior|trooper|fighter|gunner/i.test(o.name)&&o.weapons.some(w=>w.kind==='ranged')))||t.operatives.find(o=>o.weapons.some(w=>w.kind==='ranged'))||t.operatives[0];return {teamId:t.id,operativeId:o.id,rangedId:(o.weapons.find(w=>w.kind==='ranged'&&/plasma gun \(standard\)/i.test(w.name))||o.weapons.find(w=>w.kind==='ranged'))?.id||'',meleeId:o.weapons.find(w=>w.kind==='melee')?.id||'',health:o.wounds,cover:0,obscured:false,bonuses:[]};}
interface State{a:Side;b:Side;mode:Mode;first:'A'|'B';simulations:number;}
const defaults=():State=>({a:createSide('kasrkin','gunner'),b:createSide('angels-of-death','intercessor-warrior'),mode:'shoot',first:'A',simulations:15000});
function cleanSide(value:any):Side{const t=byTeam(value?.teamId);const op=t.operatives.find(o=>o.id===value?.operativeId)||t.operatives[0];const s=createSide(t.id,op.id);const fields=new Set(effectFields.map(([f])=>f));
 return {...s,rangedId:op.weapons.some(w=>w.id===value?.rangedId&&w.kind==='ranged')?value.rangedId:s.rangedId,meleeId:op.weapons.some(w=>w.id===value?.meleeId&&w.kind==='melee')?value.meleeId:s.meleeId,health:Math.round(Math.max(1,Math.min(op.wounds,Number(value?.health)||op.wounds))),cover:[0,1,2].includes(value?.cover)?value.cover:0,obscured:value?.obscured===true,bonuses:Array.isArray(value?.bonuses)?value.bonuses.slice(0,24).map((b:any)=>({id:typeof b.id==='string'?b.id.slice(0,40):uid(),name:String(b.name||'Бонус').slice(0,100),mode:['shoot','fight','both'].includes(b.mode)?b.mode:'both',enabled:b.enabled===true,sourcePage:Number(b.sourcePage)||undefined,text:String(b.text||'').slice(0,6000),effects:Array.isArray(b.effects)?b.effects.filter((e:any)=>fields.has(e.field)).slice(0,12).map((e:any)=>({field:e.field,value:Math.max(-12,Math.min(12,Number(e.value)||0)),operation:e.operation==='add'?'add':'set',max:Number.isFinite(e.max)?Math.max(0,Math.min(12,e.max)):undefined,target:['attack','defense','both'].includes(e.target)?e.target:'attack'})):[]})):[]};}
function cleanState(v:any):State{if(!v?.a||!v?.b)return defaults();return {a:cleanSide(v.a),b:cleanSide(v.b),mode:v.mode==='fight'?'fight':'shoot',first:v.first==='B'?'B':'A',simulations:[15000,50000,150000].includes(v.simulations)?v.simulations:15000};}
function loadState():State{try{const text=new URLSearchParams(window.location.search).get('duel');if(text&&text.length<40000){const bytes=Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));return cleanState(JSON.parse(new TextDecoder().decode(bytes)));}const saved=localStorage.getItem('companion-combat-last');return saved?cleanState(JSON.parse(saved)):defaults();}catch{return defaults();}}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="sim-field"><span>{label}</span>{children}</label>;}
function WeaponLine({weapon}:{weapon?:Weapon}){if(!weapon)return <p className="sim-empty-weapon">Нет подходящего оружия</p>;return <div className="weapon-line"><span><b>{weapon.attacks}</b> ATK</span><span><b>{weapon.hit}+</b> HIT</span><span><b>{weapon.normal}/{weapon.critical}</b> DMG</span><small>{weapon.rules||'Без специальных правил'}</small></div>;}
const commonBonuses=[['Balanced','Переброс · Balanced'],['Ceaseless','Переброс · Ceaseless'],['Relentless','Переброс · Relentless'],['JustAScratch','Just a Scratch'],['CurseOfRot','Curse of Rot'],['MysticScryBuff','Mystic Scry'],['Indomitus','Indomitus'],['PuritySeal','Purity Seal'],['saintlyRelics','Saintly Relics']];
function BonusEditor({bonus,teamId,onChange,onRemove}:{bonus:Bonus;teamId:string;onChange:(b:Bonus)=>void;onRemove:()=>void}){
 const [expanded,setExpanded]=React.useState(bonus.effects.length===0);
 const changeEffect=(i:number,patch:Partial<Effect>)=>onChange({...bonus,effects:bonus.effects.map((e,j)=>j===i?{...e,...patch}:e)});
 return <div className={'bonus-card'+(bonus.enabled?' enabled':'')}><div className="bonus-heading"><label><input type="checkbox" checked={bonus.enabled} onChange={e=>onChange({...bonus,enabled:e.target.checked})}/><span>{bonus.name}</span></label><button className="icon-button" onClick={onRemove} aria-label={'Удалить '+bonus.name}>×</button></div>
 <div className="bonus-summary">{bonus.effects.length?bonus.effects.map(effectLabel).join(' · '):'Нет настроенных эффектов для расчёта'}</div>
 <details open={expanded} onToggle={e=>setExpanded((e.currentTarget as HTMLDetailsElement).open)}><summary>Условия и эффекты</summary>
 {bonus.text&&<p className="source-wording">{bonus.text}</p>}{bonus.sourcePage&&<a target="_blank" rel="noreferrer" href={`/library/${teamId}.pdf#page=${bonus.sourcePage}`}>Открыть правило в PDF · стр. {bonus.sourcePage} ↗</a>}
 <Field label="Где применяется"><select value={bonus.mode} onChange={e=>onChange({...bonus,mode:e.target.value as Mode|'both'})}><option value="both">Стрельба и ближний бой</option><option value="shoot">Только стрельба</option><option value="fight">Только ближний бой</option></select></Field>
 {bonus.effects.map((effect,i)=><div className="effect-editor" key={i}><select aria-label={`Эффект ${i+1}`} value={effect.field} onChange={e=>changeEffect(i,{field:e.target.value,value:1})}>{effectFields.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>
 {!effect.field.startsWith('ability:')&&<><select aria-label="Операция" value={effect.operation} onChange={e=>changeEffect(i,{operation:e.target.value as 'set'|'add'})}><option value="set">Установить</option><option value="add">Прибавить</option></select><input aria-label="Значение эффекта" type="number" min={-12} max={12} value={effect.value} onChange={e=>changeEffect(i,{value:Number(e.target.value)})}/></>}
 <select aria-label="К чему применяется" value={effect.target} onChange={e=>changeEffect(i,{target:e.target.value as Effect['target']})}><option value="attack">Моё оружие</option><option value="defense">Моя защита</option><option value="both">Оружие и защита</option></select><button className="icon-button" aria-label="Удалить эффект" onClick={()=>onChange({...bonus,effects:bonus.effects.filter((_,j)=>i!==j)})}>×</button></div>)}
 <button className="text-button" onClick={()=>onChange({...bonus,effects:[...bonus.effects,{field:'autoNorms',value:1,operation:'set',target:'attack'}]})}>+ Добавить эффект</button>
 <p className="microcopy">Правило включается при добавлении. Если его условия не выполнены, снимите галочку. Проверьте выбранное оружие, дистанцию и ограничения из PDF.</p>
 </details></div>;
}
function OperativeCard({side,letter,mode,onChange}:{side:Side;letter:'A'|'B';mode:Mode;onChange:(s:Side)=>void}){
 const team=byTeam(side.teamId);const op=team.operatives.find(o=>o.id===side.operativeId)||team.operatives[0];const ranged=op.weapons.filter(w=>w.kind==='ranged');const melee=op.weapons.filter(w=>w.kind==='melee');
 const [ruleId,setRuleId]=React.useState('');const [common,setCommon]=React.useState('Balanced');const [customName,setCustomName]=React.useState('');
 const rules=[...team.rules,...(op.rulesText?[{id:'operative-rules',name:'Способности '+op.name,category:'OPERATIVE',text:op.rulesText,sourcePage:op.sourcePage}]:[])];
 const add=(bonus:Bonus)=>onChange({...side,bonuses:[...side.bonuses,bonus]});
 const addRule=()=>{const rule=rules.find(r=>r.id===ruleId);if(rule){add(sourceBonus(rule.name,rule.text,rule.sourcePage));setRuleId('');}};
 const addCommon=()=>{const field=common==='saintlyRelics'?'saintlyRelics':'ability:'+common;add({id:uid(),name:commonBonuses.find(([id])=>id===common)?.[1]||common,mode:'both',enabled:true,effects:[{field,value:1,operation:'set',target:['JustAScratch','saintlyRelics','Indomitus'].includes(common)?'defense':common==='CurseOfRot'?'both':'attack'}]});};
 return <section className={'operative-card side-'+letter.toLowerCase()} aria-label={'Оперативник '+letter}><div className="operative-heading"><span className="side-letter">{letter}</span><div><small>ОПЕРАТИВНИК {letter}</small><h2>{op.name}</h2></div><a className="pdf-link" title="Карточка в официальном PDF" href={`/library/${team.id}.pdf#page=${op.sourcePage}`} target="_blank" rel="noreferrer">PDF ↗</a></div>
 <div className="operative-body"><Field label="Команда"><select aria-label={'Команда '+letter} value={team.id} onChange={e=>{onChange(createSide(e.target.value));setRuleId('');}}>{usableTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>
 <Field label="Оперативник"><select aria-label={'Оперативник '+letter} value={op.id} onChange={e=>{onChange(createSide(team.id,e.target.value));setRuleId('');}}>{team.operatives.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>
 <div className="operative-stats"><div><small>APL</small><strong>{op.apl}</strong></div><div><small>MOVE</small><strong>{op.move}</strong></div><div><small>SAVE</small><strong>{op.save}+</strong></div><div><small>WOUNDS</small><strong>{side.health}<em>/{op.wounds}</em></strong></div></div>
 <div className="health-control"><IncDecSelect id={'health-'+letter} ariaLabel={'Оставшиеся раны '+letter} label="Оставшиеся раны" values={Array.from({length:op.wounds},(_,i)=>String(i+1))} selectedValue={side.health} valueChangeHandler={value=>onChange({...side,health:Number(value)})}/><span>{side.health<op.wounds/2?'Injured · HIT хуже на 1':'В строю'}</span></div>
 {mode==='shoot'&&<div className="weapon-block"><Field label="Стрелковое оружие"><select aria-label={'Стрелковое оружие '+letter} disabled={!ranged.length} value={side.rangedId} onChange={e=>onChange({...side,rangedId:e.target.value})}>{!ranged.length&&<option value="">Нет стрелкового оружия</option>}{ranged.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><WeaponLine weapon={ranged.find(w=>w.id===side.rangedId)}/></div>}
 {mode==='fight'&&<div className="weapon-block"><Field label="Оружие ближнего боя"><select aria-label={'Оружие ближнего боя '+letter} disabled={!melee.length} value={side.meleeId} onChange={e=>onChange({...side,meleeId:e.target.value})}>{!melee.length&&<option value="">Нет оружия ближнего боя</option>}{melee.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><WeaponLine weapon={melee.find(w=>w.id===side.meleeId)}/></div>}
 {mode==='shoot'&&<div className="defense-controls"><IncDecSelect id={'cover-'+letter} ariaLabel={'Укрытие '+letter} label="Сохранённые сейвы за укрытие" values={['Нет','1 normal','2 normal']} selectedValue={['Нет','1 normal','2 normal'][side.cover]} valueChangeHandler={value=>onChange({...side,cover:['Нет','1 normal','2 normal'].indexOf(value)})}/><label className="check-label"><input type="checkbox" checked={side.obscured} onChange={e=>onChange({...side,obscured:e.target.checked})}/>Obscured</label></div>}
 <details className="bonuses-panel"><summary>Бонусы и правила <span>{side.bonuses.filter(b=>b.enabled&&(b.mode===mode||b.mode==='both')).length} активно</span></summary><p className="microcopy">Добавленные правила сразу включены. Базовые свойства оружия уже учтены.</p>
 <div className="add-rule"><select aria-label={'Правило команды '+letter} value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">Выберите правило команды…</option>{rules.map(rule=><option key={rule.id} value={rule.id}>{rule.name}</option>)}</select><button disabled={!ruleId} onClick={addRule}>Добавить</button></div>
 <div className="add-rule"><select aria-label={'Быстрый бонус '+letter} value={common} onChange={e=>setCommon(e.target.value)}>{commonBonuses.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button onClick={addCommon}>+ Бонус</button></div>
 {side.bonuses.map((bonus,i)=><BonusEditor key={bonus.id} bonus={bonus} teamId={team.id} onChange={b=>onChange({...side,bonuses:side.bonuses.map((x,j)=>i===j?b:x)})} onRemove={()=>onChange({...side,bonuses:side.bonuses.filter((_,j)=>i!==j)})}/>)}
 <div className="add-rule"><input aria-label={'Название своего правила '+letter} placeholder="Название своего правила" value={customName} onChange={e=>setCustomName(e.target.value)}/><button disabled={!customName.trim()} onClick={()=>{add({id:uid(),name:customName.trim(),mode:'both',enabled:true,effects:[]});setCustomName('');}}>+ Правило</button></div>
 </details></div></section>;
}
function Distribution({data,label,color='a'}:{data:[number,number][];label:string;color?:string}){const max=Math.max(...data.map(([,p])=>p),0.01);return <div className={'distribution chart-'+color}><div className="chart-heading"><span>{label}</span><span>Вероятность, %</span></div><div className="chart-bars" role="img" aria-label={label}>{data.filter(([,p])=>p>0.0001).map(([n,p])=><div className="chart-column" key={n} title={`${n}: ${pct(p)}`}><span className="chart-prob">{p>=.05?(p*100).toFixed(0)+'%':''}</span><div className="chart-bar" style={{height:Math.max(2,p/max*100)+'px'}}/><span className="chart-axis">{n}</span></div>)}</div><details className="distribution-table"><summary>Точные значения распределения</summary><table><thead><tr><th>{label}</th><th>Вероятность</th></tr></thead><tbody>{data.map(([n,p])=><tr key={n}><td>{n}</td><td>{(p*100).toFixed(3)}%</td></tr>)}</tbody></table></details></div>;}

function Simulation(){
 const [state,setState]=React.useState<State>(loadState);
 const calc=useCalculationWorker<Omit<Job,'id'>,Result>(createSimulationWorker);
 const {result,stamp,busy,error}=calc;
 const [example,setExample]=React.useState('');
 const [saved,setSaved]=React.useState<{name:string;state:State}[]>(()=>{try{const data=JSON.parse(localStorage.getItem('companion-combat-scenarios')||'[]');return Array.isArray(data)?data.filter(x=>x&&typeof x.name==='string'&&x.state).slice(0,20).map(x=>({name:x.name.slice(0,100),state:cleanState(x.state)})):[];}catch{return [];}});
 React.useEffect(()=>{document.title='Симуляция | Companion Combat Lab';},[]);
 React.useEffect(()=>{localStorage.setItem('companion-combat-last',JSON.stringify(state));},[state]);
 const clear=calc.clear;
 React.useEffect(()=>{const pop=()=>{setState(loadState());clear();};window.addEventListener('popstate',pop);return ()=>window.removeEventListener('popstate',pop);},[clear]);
 const ta=byTeam(state.a.teamId),tb=byTeam(state.b.teamId);const ma=makeModels(state.a,ta,state.mode),mb=makeModels(state.b,tb,state.mode);const first=state.first==='A';const attackSide=first?state.a:state.b;const canRun=state.mode==='fight'?!!state.a.meleeId&&!!state.b.meleeId:!!attackSide.rangedId;
 const change=(patch:Partial<State>)=>{if(patch.mode&&patch.mode!==state.mode)calc.clear();setState(s=>({...s,...patch}));setExample('');};
 const dirty=!!result&&stamp!==JSON.stringify(state);
 const run=()=>{
   if(!ma||!mb||!canRun)return;setExample('');
   if(state.mode==='shoot'){const shooter=first?ma:mb;const target=first?mb:ma;const targetSide=first?state.b:state.a;if(/\bSaturate\b/i.test(shooter.weapon.rules))target.defense.autoNorms=Math.max(0,target.defense.autoNorms-targetSide.cover);}
   calc.run({mode:state.mode,a:pack(state.mode==='shoot'?(first?ma.attack:mb.attack):ma.attack),b:pack(state.mode==='shoot'?(first?mb.defense:ma.defense):mb.attack),first:state.first,simulations:state.simulations,targetStartingWounds:first?mb.op.wounds:ma.op.wounds},JSON.stringify(state));
 };
 const getShareUrl=()=>{const bytes=new TextEncoder().encode(JSON.stringify(state));const encoded=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=new URL('/simulation',window.location.origin);url.searchParams.set('duel',encoded);return url.href;};
 const sample=()=>{if(!result)return;const draw=(data:[number,number][])=>{const roll=Math.random();let p=0;for(const [value,chance] of data){p+=chance;if(roll<=p)return value;}return data[data.length-1]?.[0]||0;};if(result.mode==='shoot'){const n=draw(result.distributionA);setExample(`Один возможный исход: ${n} урона. ${n>=(first?state.b.health:state.a.health)?'Цель выведена из строя.':'Цель остаётся в строю.'}`);}else setExample(`Один возможный исход: A — ${draw(result.distributionA)} ран, B — ${draw(result.distributionB)} ран. Это отдельные примеры распределений, не общий бросок боя.`);};
 const save=(name:string)=>{const next=[{name,state},...saved.filter(s=>s.name!==name)].slice(0,20);localStorage.setItem('companion-combat-scenarios',JSON.stringify(next));setSaved(next);};
 const activeCount=[...state.a.bonuses,...state.b.bonuses].filter(b=>b.enabled&&(b.mode===state.mode||b.mode==='both')).length;
 return <main className="lab-shell sim-shell">
 <PageHeading eyebrow="KILL TEAM 2024 / СИМУЛЯЦИЯ" title="Оперативник против оперативника" description="Выберите профили. Добавьте бонусы. Сравните шансы." actions={<ScenarioActions getShareUrl={getShareUrl} saved={saved} onSave={save} onRestore={index=>{if(saved[index]){setState(cleanState(saved[index].state));calc.clear();setExample('');}}}/>}/>

 <div className="lab-toolbar"><ModeSwitch mode={state.mode} onChange={mode=>change({mode})}/><div className="sim-scenario-picker"><span>Быстрый сценарий</span><select aria-label="Быстрый сценарий" defaultValue="" onChange={e=>{if(!e.target.value)return;const pairs:Record<string,[string,string]>={plasma:['kasrkin','angels-of-death'],vespid:['vespid-stingwings','plague-marines'],melee:['blades-of-khaine','kommandos']};const pair=pairs[e.target.value];change({a:createSide(pair[0],e.target.value==='plasma'?'gunner':e.target.value==='vespid'?'vespid-warrior':'howling-banshee-warrior'),b:createSide(pair[1],e.target.value==='plasma'?'intercessor-warrior':e.target.value==='vespid'?'plague-marine-warrior':'kommando-boy'),mode:e.target.value==='melee'?'fight':'shoot',first:'A'});e.target.value='';}}><option value="">Выбрать…</option><option value="plasma">Kasrkin vs Angels of Death</option><option value="vespid">Vespid vs Plague Marines</option><option value="melee">Blades of Khaine vs Kommandos</option></select></div></div>
 <div className="duel-grid"><OperativeCard mode={state.mode} side={state.a} letter="A" onChange={a=>change({a})}/><div className="versus-column"><span>VS</span><button title="Поменять местами" aria-label="Поменять оперативников местами" onClick={()=>change({a:state.b,b:state.a})}>⇄</button></div><OperativeCard mode={state.mode} side={state.b} letter="B" onChange={b=>change({b})}/></div>
 <RunPanel context={state.mode==='shoot'?'Одна атака · точное распределение':'Один бой · стратегия Max Damage'} detail={activeCount?`${activeCount} активных бонусов`:'Базовые профили без дополнительных бонусов'} busy={busy} disabled={!canRun} onRun={run} onCancel={calc.cancel}>
 <Field label={state.mode==='shoot'?'Кто стреляет':'Кто наносит первый удар'}><select aria-label="Инициатор" value={state.first} onChange={e=>change({first:e.target.value as 'A'|'B'})}><option value="A">A → B</option><option value="B">B → A</option></select></Field>
 {state.mode==='fight'&&<Field label="Точность оценки"><select aria-label="Точность оценки" value={state.simulations} onChange={e=>change({simulations:Number(e.target.value)})}><option value={15000}>15 000 боёв · быстро</option><option value={50000}>50 000 боёв</option><option value={150000}>150 000 боёв · точнее</option></select></Field>}
 </RunPanel>
 {!canRun&&<p className="sim-error">Для выбранного режима нужно подходящее оружие у {state.mode==='shoot'?'стреляющего':'обоих оперативников'}.</p>}
 <section className="results-panel" aria-live="polite" aria-busy={busy}>
 <ResultsHeader hasResult={!!result} extra={result&&<span className="calculation-label">{result.mode==='shoot'?'EXACT':'MONTE CARLO'} · {Math.round(result.elapsed)} мс</span>}/>
 <ResultNotice busy={busy} dirty={dirty} error={error}/>
 {!result?<EmptyResult/>:<>
 {result.mode==='shoot'?<><div className="result-metrics"><div><span>ВЫВЕСТИ ЦЕЛЬ ИЗ СТРОЯ</span><strong>{pct(result.killA)}</strong><small>за одну атаку</small></div><div><span>СРЕДНИЙ УРОН</span><strong>{result.avgA.toFixed(2)}</strong><small>включая урон сверх оставшихся ран</small></div><div><span>РАНИТЬ ИЛИ ВЫВЕСТИ ИЗ СТРОЯ</span><strong>{pct(result.injury)}</strong><small>оставить меньше половины ран или убить</small></div></div><Distribution data={result.distributionA} label="Нанесённый урон"/></>:<><div className="result-metrics"><div><span>A ВЫВОДИТ B ИЗ СТРОЯ</span><strong>{pct(result.killA)}</strong><small>95% интервал: {interval(result.killA,result.simulations)}</small></div><div><span>B ВЫВОДИТ A ИЗ СТРОЯ</span><strong>{pct(result.killB)}</strong><small>95% интервал: {interval(result.killB,result.simulations)}</small></div><div><span>СРЕДНИЕ ОСТАВШИЕСЯ РАНЫ</span><strong className="dual-average">{result.avgA.toFixed(2)}<em>/</em>{result.avgB.toFixed(2)}</strong><small>A / B · {result.simulations.toLocaleString('ru-RU')} симуляций</small></div></div><div className="fight-charts"><Distribution data={result.distributionA} label="Оставшиеся раны A"/><Distribution data={result.distributionB} label="Оставшиеся раны B" color="b"/></div></>}
 <div className="result-actions">{result.mode==='shoot'&&<button disabled={!!dirty} onClick={sample}>Один возможный исход</button>}<span>{result.mode==='fight'?'Фиксированный seed · повторяемая статистическая оценка':'Вероятности рассчитаны перебором исходов кубиков'}</span></div>{example&&<p className="example-outcome">{example}</p>}
 </>}
 </section>
 <details className="lab-notes simulation-notes"><summary>Источники и границы расчёта</summary><p>Официальная библиотека: {catalog.counts.teams} команд, {catalog.counts.operatives} оперативников, {catalog.counts.weapons} профилей оружия. Снимок от 25 сентября 2026. Изменения после этой даты здесь не учтены.</p><p>Моделируется одна цель и одна атака / один ближний бой. Range, Blast, Torrent, Hot, Stun, перемещение, видимость, CP и последствия после действия не разыгрываются автоматически. Укрытие и Obscured задаются вручную. При оставшихся ранах ниже половины исходных HIT ухудшается на 1.</p><p>Способности оперативника и команды включаются через бонусы. Предложенное соответствие текста правил параметрам можно изменить. Условия, ограничения по оружию и возможность совместного применения подтверждает пользователь. Сохраняются ограничения и допущения исходного ядра ktcalc; выбор ударов и парирований использует его эвристики.</p><p><a href="/help" target="_blank" rel="noreferrer">Справка исходного калькулятора ↗</a> · <a href="/api/health" target="_blank" rel="noreferrer">Статус локального сервиса ↗</a></p></details>
 </main>;
}
export default Simulation;
